// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/yandex-food/yandex-food.proto

package yandex_food

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FoodCard struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ImageUrl             string   `protobuf:"bytes,2,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Id                   string   `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	RestarauntName       string   `protobuf:"bytes,5,opt,name=restarauntName,proto3" json:"restarauntName,omitempty"`
	Price                float32  `protobuf:"fixed32,6,opt,name=price,proto3" json:"price,omitempty"`
	RestarauntUrl        string   `protobuf:"bytes,7,opt,name=restarauntUrl,proto3" json:"restarauntUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodCard) Reset()         { *m = FoodCard{} }
func (m *FoodCard) String() string { return proto.CompactTextString(m) }
func (*FoodCard) ProtoMessage()    {}
func (*FoodCard) Descriptor() ([]byte, []int) {
	return fileDescriptor_63485ca4292eb4d3, []int{0}
}

func (m *FoodCard) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodCard.Unmarshal(m, b)
}
func (m *FoodCard) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodCard.Marshal(b, m, deterministic)
}
func (m *FoodCard) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodCard.Merge(m, src)
}
func (m *FoodCard) XXX_Size() int {
	return xxx_messageInfo_FoodCard.Size(m)
}
func (m *FoodCard) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodCard.DiscardUnknown(m)
}

var xxx_messageInfo_FoodCard proto.InternalMessageInfo

func (m *FoodCard) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FoodCard) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *FoodCard) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *FoodCard) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FoodCard) GetRestarauntName() string {
	if m != nil {
		return m.RestarauntName
	}
	return ""
}

func (m *FoodCard) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *FoodCard) GetRestarauntUrl() string {
	if m != nil {
		return m.RestarauntUrl
	}
	return ""
}

type FoodFilter struct {
	KitchenWhiteList     []string `protobuf:"bytes,1,rep,name=kitchenWhiteList,proto3" json:"kitchenWhiteList,omitempty"`
	RestarauntWhiteList  []string `protobuf:"bytes,2,rep,name=restarauntWhiteList,proto3" json:"restarauntWhiteList,omitempty"`
	KitchenBlackList     []string `protobuf:"bytes,3,rep,name=kitchenBlackList,proto3" json:"kitchenBlackList,omitempty"`
	RestarauntBlackList  []string `protobuf:"bytes,4,rep,name=restarauntBlackList,proto3" json:"restarauntBlackList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodFilter) Reset()         { *m = FoodFilter{} }
func (m *FoodFilter) String() string { return proto.CompactTextString(m) }
func (*FoodFilter) ProtoMessage()    {}
func (*FoodFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_63485ca4292eb4d3, []int{1}
}

func (m *FoodFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodFilter.Unmarshal(m, b)
}
func (m *FoodFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodFilter.Marshal(b, m, deterministic)
}
func (m *FoodFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodFilter.Merge(m, src)
}
func (m *FoodFilter) XXX_Size() int {
	return xxx_messageInfo_FoodFilter.Size(m)
}
func (m *FoodFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodFilter.DiscardUnknown(m)
}

var xxx_messageInfo_FoodFilter proto.InternalMessageInfo

func (m *FoodFilter) GetKitchenWhiteList() []string {
	if m != nil {
		return m.KitchenWhiteList
	}
	return nil
}

func (m *FoodFilter) GetRestarauntWhiteList() []string {
	if m != nil {
		return m.RestarauntWhiteList
	}
	return nil
}

func (m *FoodFilter) GetKitchenBlackList() []string {
	if m != nil {
		return m.KitchenBlackList
	}
	return nil
}

func (m *FoodFilter) GetRestarauntBlackList() []string {
	if m != nil {
		return m.RestarauntBlackList
	}
	return nil
}

type FoodRequest struct {
	CardsNum             int64    `protobuf:"varint,1,opt,name=cardsNum,proto3" json:"cardsNum,omitempty"`
	SelectedTags         []string `protobuf:"bytes,2,rep,name=selectedTags,proto3" json:"selectedTags,omitempty"`
	Longitude            float32  `protobuf:"fixed32,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude             float32  `protobuf:"fixed32,4,opt,name=latitude,proto3" json:"latitude,omitempty"`
	GetTags              bool     `protobuf:"varint,5,opt,name=getTags,proto3" json:"getTags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodRequest) Reset()         { *m = FoodRequest{} }
func (m *FoodRequest) String() string { return proto.CompactTextString(m) }
func (*FoodRequest) ProtoMessage()    {}
func (*FoodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_63485ca4292eb4d3, []int{2}
}

func (m *FoodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodRequest.Unmarshal(m, b)
}
func (m *FoodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodRequest.Marshal(b, m, deterministic)
}
func (m *FoodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodRequest.Merge(m, src)
}
func (m *FoodRequest) XXX_Size() int {
	return xxx_messageInfo_FoodRequest.Size(m)
}
func (m *FoodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FoodRequest proto.InternalMessageInfo

func (m *FoodRequest) GetCardsNum() int64 {
	if m != nil {
		return m.CardsNum
	}
	return 0
}

func (m *FoodRequest) GetSelectedTags() []string {
	if m != nil {
		return m.SelectedTags
	}
	return nil
}

func (m *FoodRequest) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *FoodRequest) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *FoodRequest) GetGetTags() bool {
	if m != nil {
		return m.GetTags
	}
	return false
}

type FoodResponse struct {
	FoodCards            []*FoodCard `protobuf:"bytes,1,rep,name=foodCards,proto3" json:"foodCards,omitempty"`
	AvailableTags        []string    `protobuf:"bytes,2,rep,name=availableTags,proto3" json:"availableTags,omitempty"`
	Succeed              bool        `protobuf:"varint,3,opt,name=succeed,proto3" json:"succeed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FoodResponse) Reset()         { *m = FoodResponse{} }
func (m *FoodResponse) String() string { return proto.CompactTextString(m) }
func (*FoodResponse) ProtoMessage()    {}
func (*FoodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_63485ca4292eb4d3, []int{3}
}

func (m *FoodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodResponse.Unmarshal(m, b)
}
func (m *FoodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodResponse.Marshal(b, m, deterministic)
}
func (m *FoodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodResponse.Merge(m, src)
}
func (m *FoodResponse) XXX_Size() int {
	return xxx_messageInfo_FoodResponse.Size(m)
}
func (m *FoodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FoodResponse proto.InternalMessageInfo

func (m *FoodResponse) GetFoodCards() []*FoodCard {
	if m != nil {
		return m.FoodCards
	}
	return nil
}

func (m *FoodResponse) GetAvailableTags() []string {
	if m != nil {
		return m.AvailableTags
	}
	return nil
}

func (m *FoodResponse) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

type FoodFromCollectionRequest struct {
	CardsNum             int64    `protobuf:"varint,1,opt,name=cardsNum,proto3" json:"cardsNum,omitempty"`
	FoodIds              []int64  `protobuf:"varint,2,rep,packed,name=foodIds,proto3" json:"foodIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FoodFromCollectionRequest) Reset()         { *m = FoodFromCollectionRequest{} }
func (m *FoodFromCollectionRequest) String() string { return proto.CompactTextString(m) }
func (*FoodFromCollectionRequest) ProtoMessage()    {}
func (*FoodFromCollectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_63485ca4292eb4d3, []int{4}
}

func (m *FoodFromCollectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodFromCollectionRequest.Unmarshal(m, b)
}
func (m *FoodFromCollectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodFromCollectionRequest.Marshal(b, m, deterministic)
}
func (m *FoodFromCollectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodFromCollectionRequest.Merge(m, src)
}
func (m *FoodFromCollectionRequest) XXX_Size() int {
	return xxx_messageInfo_FoodFromCollectionRequest.Size(m)
}
func (m *FoodFromCollectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodFromCollectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FoodFromCollectionRequest proto.InternalMessageInfo

func (m *FoodFromCollectionRequest) GetCardsNum() int64 {
	if m != nil {
		return m.CardsNum
	}
	return 0
}

func (m *FoodFromCollectionRequest) GetFoodIds() []int64 {
	if m != nil {
		return m.FoodIds
	}
	return nil
}

type FoodFromCollectionResponse struct {
	FoodCards            []*FoodCard `protobuf:"bytes,1,rep,name=foodCards,proto3" json:"foodCards,omitempty"`
	Succeed              bool        `protobuf:"varint,2,opt,name=succeed,proto3" json:"succeed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FoodFromCollectionResponse) Reset()         { *m = FoodFromCollectionResponse{} }
func (m *FoodFromCollectionResponse) String() string { return proto.CompactTextString(m) }
func (*FoodFromCollectionResponse) ProtoMessage()    {}
func (*FoodFromCollectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_63485ca4292eb4d3, []int{5}
}

func (m *FoodFromCollectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FoodFromCollectionResponse.Unmarshal(m, b)
}
func (m *FoodFromCollectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FoodFromCollectionResponse.Marshal(b, m, deterministic)
}
func (m *FoodFromCollectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FoodFromCollectionResponse.Merge(m, src)
}
func (m *FoodFromCollectionResponse) XXX_Size() int {
	return xxx_messageInfo_FoodFromCollectionResponse.Size(m)
}
func (m *FoodFromCollectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FoodFromCollectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FoodFromCollectionResponse proto.InternalMessageInfo

func (m *FoodFromCollectionResponse) GetFoodCards() []*FoodCard {
	if m != nil {
		return m.FoodCards
	}
	return nil
}

func (m *FoodFromCollectionResponse) GetSucceed() bool {
	if m != nil {
		return m.Succeed
	}
	return false
}

func init() {
	proto.RegisterType((*FoodCard)(nil), "yandex_food.FoodCard")
	proto.RegisterType((*FoodFilter)(nil), "yandex_food.FoodFilter")
	proto.RegisterType((*FoodRequest)(nil), "yandex_food.FoodRequest")
	proto.RegisterType((*FoodResponse)(nil), "yandex_food.FoodResponse")
	proto.RegisterType((*FoodFromCollectionRequest)(nil), "yandex_food.FoodFromCollectionRequest")
	proto.RegisterType((*FoodFromCollectionResponse)(nil), "yandex_food.FoodFromCollectionResponse")
}

func init() {
	proto.RegisterFile("api/yandex-food/yandex-food.proto", fileDescriptor_63485ca4292eb4d3)
}

var fileDescriptor_63485ca4292eb4d3 = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0x6b, 0x14, 0x31,
	0x14, 0x65, 0x66, 0xb6, 0xdd, 0xdd, 0xbb, 0x6d, 0x91, 0xa8, 0x90, 0x2e, 0x3e, 0xac, 0x83, 0xc8,
	0x22, 0xb8, 0x4a, 0xfb, 0xe8, 0x5b, 0x2b, 0x15, 0x41, 0x0a, 0x06, 0x45, 0xf4, 0x45, 0xd2, 0xc9,
	0xed, 0x36, 0xec, 0x4c, 0x32, 0x26, 0x19, 0xd1, 0x67, 0x7f, 0x89, 0xff, 0xc6, 0x47, 0x7f, 0x92,
	0x24, 0xb3, 0x3b, 0x1f, 0xdd, 0x7d, 0x10, 0xfa, 0x96, 0x7b, 0xce, 0xc9, 0xc9, 0xb9, 0xb9, 0x99,
	0x81, 0xc7, 0xbc, 0x94, 0x2f, 0x7e, 0x72, 0x25, 0xf0, 0xc7, 0xf3, 0x6b, 0xad, 0x45, 0x77, 0xbd,
	0x28, 0x8d, 0x76, 0x9a, 0x4c, 0x6a, 0xe8, 0xab, 0x87, 0xd2, 0xbf, 0x11, 0x8c, 0x2e, 0xb4, 0x16,
	0xe7, 0xdc, 0x08, 0x42, 0x60, 0xa0, 0x78, 0x81, 0x34, 0x9a, 0x45, 0xf3, 0x31, 0x0b, 0x6b, 0x32,
	0x85, 0x91, 0x2c, 0xf8, 0x12, 0x3f, 0x9a, 0x9c, 0xc6, 0x01, 0x6f, 0x6a, 0x32, 0x83, 0x89, 0x40,
	0x9b, 0x19, 0x59, 0x3a, 0xa9, 0x15, 0x4d, 0x02, 0xdd, 0x85, 0xc8, 0x11, 0xc4, 0x52, 0xd0, 0x41,
	0x20, 0x62, 0x29, 0xc8, 0x53, 0x38, 0x32, 0x68, 0x1d, 0x37, 0xbc, 0x52, 0xee, 0xd2, 0x9f, 0xb5,
	0x17, 0xb8, 0x5b, 0x28, 0x79, 0x00, 0x7b, 0xa5, 0x91, 0x19, 0xd2, 0xfd, 0x59, 0x34, 0x8f, 0x59,
	0x5d, 0x90, 0x27, 0x70, 0xd8, 0xea, 0x7c, 0xa0, 0x61, 0xd8, 0xdc, 0x07, 0xd3, 0x3f, 0x11, 0x80,
	0x6f, 0xe9, 0x42, 0xe6, 0x0e, 0x0d, 0x79, 0x06, 0xf7, 0x56, 0xd2, 0x65, 0x37, 0xa8, 0x3e, 0xdd,
	0x48, 0x87, 0xef, 0xa4, 0x75, 0x34, 0x9a, 0x25, 0xf3, 0x31, 0xdb, 0xc2, 0xc9, 0x4b, 0xb8, 0xdf,
	0x7a, 0xb5, 0xf2, 0x38, 0xc8, 0x77, 0x51, 0x1d, 0xf7, 0xb3, 0x9c, 0x67, 0xab, 0x20, 0x4f, 0x7a,
	0xee, 0x0d, 0xde, 0x77, 0x6f, 0xe5, 0x83, 0xdb, 0xee, 0x0d, 0x95, 0xfe, 0x8e, 0x60, 0xe2, 0x5b,
	0x61, 0xf8, 0xad, 0x42, 0xeb, 0xfc, 0x30, 0x32, 0x6e, 0x84, 0xbd, 0xac, 0x8a, 0x30, 0xa4, 0x84,
	0x35, 0x35, 0x49, 0xe1, 0xc0, 0x62, 0x8e, 0x99, 0x43, 0xf1, 0x81, 0x2f, 0xed, 0x3a, 0x74, 0x0f,
	0x23, 0x8f, 0x60, 0x9c, 0x6b, 0xb5, 0x94, 0xae, 0x12, 0x18, 0xc6, 0x15, 0xb3, 0x16, 0xf0, 0xee,
	0x39, 0x77, 0x35, 0x39, 0x08, 0x64, 0x53, 0x13, 0x0a, 0xc3, 0x25, 0xba, 0x60, 0xec, 0x27, 0x36,
	0x62, 0x9b, 0x32, 0xfd, 0x15, 0xc1, 0x41, 0x9d, 0xd1, 0x96, 0x5a, 0x59, 0x24, 0xa7, 0x30, 0xbe,
	0x5e, 0xbf, 0x28, 0x1b, 0x6e, 0x7a, 0x72, 0xf2, 0x70, 0xd1, 0x79, 0x73, 0x8b, 0xcd, 0x7b, 0x63,
	0xad, 0xce, 0x8f, 0x96, 0x7f, 0xe7, 0x32, 0xe7, 0x57, 0x39, 0x76, 0xe2, 0xf7, 0x41, 0x9f, 0xc2,
	0x56, 0x59, 0x86, 0x28, 0x42, 0xfa, 0x11, 0xdb, 0x94, 0xe9, 0x7b, 0x38, 0x0e, 0x33, 0x37, 0xba,
	0x38, 0xd7, 0xb9, 0x6f, 0x59, 0x6a, 0xf5, 0x3f, 0xd7, 0x46, 0x61, 0xe8, 0x53, 0xbc, 0x15, 0xf5,
	0x91, 0x09, 0xdb, 0x94, 0xe9, 0x0a, 0xa6, 0xbb, 0x2c, 0xef, 0xd2, 0x65, 0x27, 0x7f, 0xdc, 0xcb,
	0x7f, 0xc2, 0x00, 0x3e, 0x87, 0xcd, 0x7e, 0x1b, 0x79, 0x0d, 0x87, 0x6f, 0xd0, 0x31, 0xae, 0x84,
	0x2e, 0x02, 0x40, 0xb7, 0xac, 0xd7, 0xbd, 0x4d, 0x8f, 0x77, 0x30, 0x75, 0xc4, 0xb3, 0xe9, 0x17,
	0xda, 0xfd, 0xfc, 0x5f, 0x75, 0x84, 0x57, 0xfb, 0xe1, 0x5f, 0x70, 0xfa, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x1c, 0x60, 0xba, 0x72, 0x30, 0x04, 0x00, 0x00,
}
