// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package yandex_food

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// YandexFoodClient is the client API for YandexFood service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type YandexFoodClient interface {
	GetRandomFood(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (*FoodResponse, error)
}

type yandexFoodClient struct {
	cc grpc.ClientConnInterface
}

func NewYandexFoodClient(cc grpc.ClientConnInterface) YandexFoodClient {
	return &yandexFoodClient{cc}
}

func (c *yandexFoodClient) GetRandomFood(ctx context.Context, in *FoodRequest, opts ...grpc.CallOption) (*FoodResponse, error) {
	out := new(FoodResponse)
	err := c.cc.Invoke(ctx, "/yandex_food.YandexFood/GetRandomFood", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// YandexFoodServer is the server API for YandexFood service.
// All implementations must embed UnimplementedYandexFoodServer
// for forward compatibility
type YandexFoodServer interface {
	GetRandomFood(context.Context, *FoodRequest) (*FoodResponse, error)
	mustEmbedUnimplementedYandexFoodServer()
}

// UnimplementedYandexFoodServer must be embedded to have forward compatible implementations.
type UnimplementedYandexFoodServer struct {
}

func (UnimplementedYandexFoodServer) GetRandomFood(context.Context, *FoodRequest) (*FoodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRandomFood not implemented")
}
func (UnimplementedYandexFoodServer) mustEmbedUnimplementedYandexFoodServer() {}

// UnsafeYandexFoodServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to YandexFoodServer will
// result in compilation errors.
type UnsafeYandexFoodServer interface {
	mustEmbedUnimplementedYandexFoodServer()
}

func RegisterYandexFoodServer(s grpc.ServiceRegistrar, srv YandexFoodServer) {
	s.RegisterService(&YandexFood_ServiceDesc, srv)
}

func _YandexFood_GetRandomFood_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FoodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(YandexFoodServer).GetRandomFood(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/yandex_food.YandexFood/GetRandomFood",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(YandexFoodServer).GetRandomFood(ctx, req.(*FoodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// YandexFood_ServiceDesc is the grpc.ServiceDesc for YandexFood service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var YandexFood_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yandex_food.YandexFood",
	HandlerType: (*YandexFoodServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRandomFood",
			Handler:    _YandexFood_GetRandomFood_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/yandex-food/yandex-food.proto",
}
